<?php

return [
    'M1' => 'El registro se guardó correctamente.',
    'M2' => 'El registro se actualizó correctamente.',
    'M3' => 'El registro fue eliminado correctamente.',
    'M4' => '¿Está seguro de que desea eliminar este registro? Esta acción no eliminará la información de forma permanente.',
    'M5' => 'La operación fue cancelada.',
    'M6' => 'Ingrese la cédula o RUC antes de continuar.',
    'M7' => 'La cédula o RUC ingresada no cumple con la longitud requerida para continuar.',
    'M8' => 'La cédula o RUC debe contener solamente números.',
    'M9' => 'La cédula o RUC ingresada no es válida.',
    'M10' => 'Ya existe un registro con la misma cédula o RUC.',
    'M11' => 'Existen campos obligatorios sin completar. Verifique e intente nuevamente.',
    'M12' => 'El RUC ingresado está incompleto.',
    'M13' => 'El RUC debe contener únicamente números.',
    'M14' => 'El RUC ingresado no es válido.',
    'M15' => 'Ya existe un registro con el mismo RUC.',
    'M16' => 'Ingrese el nombre para continuar.',
    'M17' => 'Ingrese el apellido para continuar.',
    'M18' => 'Ingrese el número telefónico.',
    'M19' => 'El número telefónico está incompleto.',
    'M20' => 'El número telefónico debe contener solo números.',
    'M21' => 'El número telefónico ingresado no es válido.',
    'M22' => 'Ingrese el correo electrónico.',
    'M23' => 'El correo electrónico ingresado no tiene un formato válido.',
    'M24' => 'Ya existe un registro con el mismo correo electrónico.',
    'M25' => 'Ingrese el nombre del producto.',
    'M26' => 'El producto ya existe en el sistema.',
    'M27' => 'El producto seleccionado no se encuentra activo.',
    'M28' => 'El producto seleccionado no está disponible.',
    'M29' => 'Ingrese el precio del producto.',
    'M30' => 'El precio debe ser un valor numérico.',
    'M31' => 'El precio no puede ser un valor negativo.',
    'M32' => 'No existe stock suficiente para el producto seleccionado.',
    'M33' => 'Ingrese la cantidad del producto.',
    'M34' => 'La cantidad debe ser un valor numérico.',
    'M35' => 'La cantidad ingresada no es válida.',
    'M36' => 'La cantidad ingresada supera el stock disponible.',
    'M37' => 'Seleccione un proveedor para continuar.',
    'M38' => 'La orden de compra no contiene productos.',
    'M39' => 'La orden de compra se registró correctamente.',
    'M40' => 'La orden de compra fue anulada correctamente.',
    'M41' => 'Seleccione una orden de compra válida.',
    'M42' => 'La cantidad recibida no es válida.',
    'M43' => 'La recepción se registró correctamente.',
    'M44' => 'Seleccione un cliente para continuar.',
    'M45' => 'La factura no contiene productos.',
    'M46' => 'La factura se generó correctamente.',
    'M47' => 'La factura fue anulada correctamente.',
    'M48' => 'La factura no puede modificarse en su estado actual.',
    'M49' => 'El carrito de compras está vacío.',
    'M50' => 'El producto fue agregado al carrito correctamente.',
    'M51' => 'El producto fue retirado del carrito correctamente.',
    'M52' => 'El carrito se actualizó correctamente.',
    'M53' => 'Seleccione un método de pago para continuar.',
    'M54' => 'La compra se realizó correctamente.',
    'M55' => 'La fecha ingresada no es válida.',
    'M56' => 'La fecha seleccionada no puede ser posterior a la fecha actual.',
    'M57' => 'Ingrese un criterio para realizar la búsqueda.',
    'M58' => 'El criterio ingresado no es válido.',
    'M59' => 'No se encontraron resultados con los criterios ingresados.',
    'M60' => 'La operación no se puede realizar en el estado actual.',
    'M61' => '¿Está seguro de realizar esta acción?',
    'M62' => 'Registro actualizado correctamente.',
    'M63' => 'La factura no puede anularse en su estado actual.',
    'M64' => 'El rango de fechas es inválido (desde no puede ser mayor que hasta).',
    'M65' => 'Debe seleccionar un cliente válido.',
    'M66' => 'El cliente seleccionado no se encuentra activo.',
    'M67' => 'No se permite agregar el mismo producto más de una vez en la factura.',
    'M68' => 'La cantidad está vacía.',
    'M69' => '¿Está seguro de aprobar esta factura? Una vez aprobada no podrá modificarse.',
    'M70' => 'Factura aprobada correctamente.',
    'M71' => 'La factura no puede aprobarse en su estado actual.',
    'M72' => 'Esta factura se encuentra aprobada o anulada. Solo está disponible para visualización.',

    //EXCEPCIONES
    'E1' => 'Falla de conexión a la base de datos.',
    'E2' => 'Tiempo de espera excedido en la base de datos.',
    'E3' => 'Error en la ejecución de consultas SQL.',
    'E4' => 'Violación de clave primaria.',
    'E5' => 'Violación de clave foránea.',
    'E6' => 'Violación de restricciones de integridad.',
    'E7' => 'Error en el manejo de transacciones.',
    'E8' => 'Error de concurrencia.',
    'E9' => 'Inconsistencia en el estado del proceso.',
    'E10' => 'Error de conversión de datos.',
    'E11' => 'Recurso del sistema no disponible.',
    'E12' => 'Error inesperado del sistema.',
    'E13' => 'Error en la generación de documentos.',
    'E14' => 'Error en la actualización de inventario.',
    'E15' => 'Error en la validación de reglas de negocio.',
    'E16' => 'Error de sesión inválida.',
    'E17' => 'Error en el procesamiento de pagos.',
    'E18' => 'Error de acceso a datos.',
    'E19' => 'Error en la carga de configuraciones.',
    'E20' => 'Error en la sincronización de procesos.',
    'gen.error' => 'Ocurrió un error inesperado.',
    'productos.crear.ok' => 'El registro se guardó correctamente.',
    'productos.actualizar.ok' => 'El registro se actualizó correctamente.',
    'productos.eliminar.ok' => 'El registro fue eliminado correctamente.',
    'productos.no.disponible' => 'La operación no se puede realizar en el estado actual.',
    'productos.duplicado' => 'El producto ya existe en el sistema.',
    'productos.sin.registros' => 'No se encontraron resultados con los criterios ingresados.',
    'productos.sin.coincidencias' => 'No se encontraron resultados con los criterios ingresados.',
    'productos.producto.vacio' => 'Ingrese el nombre del producto.',
    'productos.precio.vacio' => 'Ingrese el precio del producto.',
    'productos.precio.invalido' => 'El precio debe ser un valor numérico.',
    'productos.precio.negativo' => 'El precio no puede ser un valor negativo.',
    'productos.stock.invalido' => 'La cantidad ingresada no es válida.',
    'productos.parametro.vacio' => 'Ingrese un criterio para realizar la búsqueda.',
    'productos.parametro.invalido' => 'El criterio ingresado no es válido.',

    // ==================== CARRITO DE COMPRAS ====================
    'carrito.agregar.ok' => '¡Producto agregado al carrito!',
    'carrito.actualizar.ok' => 'Cantidad actualizada correctamente',
    'carrito.eliminar.ok' => 'Producto eliminado del carrito',
    'carrito.eliminar.confirmar' => '¿Deseas quitar este producto de tu carrito?',
    'carrito.vaciar.ok' => 'Carrito vaciado correctamente',
    'carrito.vaciar.confirmar' => '¿Estás seguro de vaciar todo tu carrito?',
    'carrito.vacio' => 'Tu carrito está vacío',

    // Validaciones de stock
    'carrito.sin.stock' => 'Lo sentimos, este producto está agotado',
    'carrito.stock.insuficiente' => 'Solo tenemos :cantidad unidades disponibles',
    'carrito.cantidad.maxima' => 'Has alcanzado el máximo disponible de este producto',
    'carrito.cantidad.invalida' => 'Por favor ingresa una cantidad válida',
    'carrito.producto.no.encontrado' => 'El producto que buscas no está disponible',
    'carrito.producto.inactivo' => 'Este producto ya no está disponible',

    // Errores generales
    'carrito.error.agregar' => 'No pudimos agregar el producto. Intenta nuevamente',
    'carrito.error.actualizar' => 'No pudimos actualizar la cantidad. Intenta nuevamente',
    'carrito.error.eliminar' => 'No pudimos eliminar el producto. Intenta nuevamente',
];

